/* eslint-env node */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'ci',
        'db',
        'revert',
        'build',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        // Applications
        'backend',
        'frontend',
        'cms-ui',
        'worker',
        // Shared packages
        'shared-ui',
        'ui',
        'types',
        'utils',
        'shared-db',
        'db',
        'validation',
        'constants',
        'logger',
        'middlewares',
        'context',
        'events',
        'repository',
        'storage',
        'config',
        'plugin',
        'plugin-sdk',
        'sdk-codegen',
        'sdk-core',
        'sdk-nextjs',
        'sdk-node',
        'sdk-react',
        'sdk',
        'typescript-config',
        'eslint-config',
        // Repository / Meta scopes
        'root',
        'release',
        'deps',
        'ci',
        'swagger',
        'all',
      ],
    ],
    'subject-min-length': [2, 'always', 10],
  },
};
