import type { SchemaRecord, SchemaField } from '@repo/types';

export function toPascalCase(str: string): string {
  return str
    .replace(/[-_]+/g, ' ')
    .replace(/[^\w\s]/g, '')
    .replace(
      /\s+(.)(\w*)/g,
      (_, $1: string, $2: string) => $1.toUpperCase() + $2.toLowerCase(),
    )
    .replace(/^\w/, (s) => s.toUpperCase())
    .replace(/\s+/g, '');
}

export function generateTypes(
  schemas: SchemaRecord[],
  timestamp: string = new Date().toISOString(),
): string {
  const lines: string[] = [];

  lines.push(
    `// Auto-generated by cms-codegen on ${timestamp} - do not edit manually`,
  );
  lines.push('');

  // Unconditionally output MediaAsset interface for type safety
  lines.push('export interface MediaAsset {');
  lines.push('  id: string;');
  lines.push('  filename: string;');
  lines.push('  mimeType: string;');
  lines.push('  sizeBytes: number;');
  lines.push('  width: number | null;');
  lines.push('  height: number | null;');
  lines.push('  url: string;');
  lines.push('  altText: string | null;');
  lines.push('  folderId: string | null;');
  lines.push('  createdAt: string;');
  lines.push('}');
  lines.push('');

  const contentMapEntries: string[] = [];

  for (const schema of schemas) {
    const interfaceName = `${toPascalCase(schema.slug)}Entry`;
    contentMapEntries.push(`  '${schema.slug}': ${interfaceName};`);

    lines.push(`export interface ${interfaceName} {`);
    lines.push('  id: string;');
    lines.push("  status: 'draft' | 'published';");
    lines.push('  data: {');

    for (const field of schema.definition.fields) {
      const fieldType = getFieldType(field);
      lines.push(`    ${field.apiId}: ${fieldType};`);
    }

    lines.push('  };');
    lines.push('}');
    lines.push('');
  }

  lines.push('export interface CmsContentMap {');
  lines.push(contentMapEntries.join('\n'));
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function mapDataType(field: SchemaField): string {
  switch (field.dataType) {
    case 'text':
    case 'richtext':
    case 'email':
    case 'url':
    case 'date':
    case 'datetime':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json':
      return 'Record<string, unknown>';
    case 'media':
      return 'MediaAsset';
    case 'relation':
      return '{ id: string }';
    case 'enum': {
      const options = field.config?.options;
      if (
        Array.isArray(options) &&
        options.every((o: unknown) => typeof o === 'string') &&
        options.length > 0
      ) {
        return options.map((o: string) => `'${o}'`).join(' | ');
      }
      return 'string';
    }
    default:
      return 'unknown';
  }
}

function getFieldType(field: SchemaField): string {
  let typeStr = mapDataType(field);
  if (field.isRepeatable) {
    typeStr = `${typeStr}[]`;
  }
  if (!field.isRequired) {
    typeStr = `${typeStr} | null`;
  }
  return typeStr;
}
