import { Router } from 'express';
import { accessRouter } from '../modules/access/access.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { contentRoutes } from '../modules/content/content.routes.js';
import { mediaRoutes } from '../modules/media/media.routes.js';
import { mediaFoldersRoutes } from '../modules/media/media-folders.routes.js';
import { webhooksRouter } from '../modules/webhooks/webhooks.routes.js';
import { localesRouter } from '../modules/locales/locales.routes.js';
import { schemaRouter } from '../modules/schemas/schema.routes.js';
import { auditRouter } from '../modules/audit/audit.routes.js';
// Versioned API router
export const apiRouter = Router();
apiRouter.use('/auth', authRouter);
apiRouter.use('/schemas', schemaRouter);
apiRouter.use('/content', contentRoutes);
apiRouter.use('/media', mediaRoutes);
apiRouter.use('/media-folders', mediaFoldersRoutes);
apiRouter.use('/access', accessRouter);
apiRouter.use('/webhooks', webhooksRouter);
apiRouter.use('/locales', localesRouter);
apiRouter.use('/audit-logs', auditRouter);
