import { describe, it, expect } from 'vitest';
import type { SchemaRecord } from '@repo/types';
import {
  generateTypes,
  toPascalCase,
} from '../../src/generators/type-generator.js';

describe('Codegen Type Generator', () => {
  it('should correctly format strings to PascalCase', () => {
    expect(toPascalCase('blog-post')).toBe('BlogPost');
    expect(toPascalCase('articles')).toBe('Articles');
    expect(toPascalCase('blog_post_example')).toBe('BlogPostExample');
  });

  it('should generate valid TypeScript types from fixture schema definitions', () => {
    const timestamp = '2026-08-25T12:00:00.000Z';
    const schemas: SchemaRecord[] = [
      {
        id: 'schema-1',
        name: 'Article',
        slug: 'articles',
        type: 'collection',
        status: 'published',
        version: 1,
        createdAt: '2026-08-25T12:00:00.000Z',
        updatedAt: '2026-08-25T12:00:00.000Z',
        definition: {
          fields: [
            {
              apiId: 'title',
              displayName: 'Title',
              dataType: 'text',
              isRequired: true,
              isUnique: false,
              isLocalized: false,
              isRepeatable: false,
              sortOrder: 1,
            },
            {
              apiId: 'body',
              displayName: 'Body',
              dataType: 'richtext',
              isRequired: false,
              isUnique: false,
              isLocalized: false,
              isRepeatable: false,
              sortOrder: 2,
            },
            {
              apiId: 'rating',
              displayName: 'Rating',
              dataType: 'number',
              isRequired: true,
              isUnique: false,
              isLocalized: false,
              isRepeatable: false,
              sortOrder: 3,
            },
            {
              apiId: 'tags',
              displayName: 'Tags',
              dataType: 'text',
              isRequired: false,
              isUnique: false,
              isLocalized: false,
              isRepeatable: true,
              sortOrder: 4,
            },
            {
              apiId: 'metadata',
              displayName: 'Metadata',
              dataType: 'json',
              isRequired: false,
              isUnique: false,
              isLocalized: false,
              isRepeatable: false,
              sortOrder: 5,
            },
            {
              apiId: 'status',
              displayName: 'Status',
              dataType: 'enum',
              isRequired: true,
              isUnique: false,
              isLocalized: false,
              isRepeatable: false,
              config: {
                options: ['draft', 'published', 'archived'],
              },
              sortOrder: 6,
            },
            {
              apiId: 'featuredImage',
              displayName: 'Featured Image',
              dataType: 'media',
              isRequired: false,
              isUnique: false,
              isLocalized: false,
              isRepeatable: false,
              sortOrder: 7,
            },
            {
              apiId: 'author',
              displayName: 'Author',
              dataType: 'relation',
              isRequired: true,
              isUnique: false,
              isLocalized: false,
              isRepeatable: false,
              sortOrder: 8,
            },
          ],
        },
      },
    ];

    const result = generateTypes(schemas, timestamp);

    // Assert overall header
    expect(result).toContain(
      `// Auto-generated by cms-codegen on ${timestamp} - do not edit manually`,
    );

    // Assert MediaAsset definition
    expect(result).toContain('export interface MediaAsset {');
    expect(result).toContain('  id: string;');
    expect(result).toContain('  url: string;');

    // Assert generated interface
    expect(result).toContain('export interface ArticlesEntry {');
    expect(result).toContain('  title: string;');
    expect(result).toContain('  body: string | null;');
    expect(result).toContain('  rating: number;');
    expect(result).toContain('  tags: string[] | null;');
    expect(result).toContain('  metadata: Record<string, unknown> | null;');
    expect(result).toContain("  status: 'draft' | 'published' | 'archived';");
    expect(result).toContain('  featuredImage: MediaAsset | null;');
    expect(result).toContain('  author: { id: string };');

    // Assert CmsContentMap
    expect(result).toContain('export interface CmsContentMap {');
    expect(result).toContain("  'articles': ArticlesEntry;");
  });
});
